### PR TITLE
Add an option to serve index.html for the homepage

### PR DESCRIPTION
**Pull request by synw**
This adds a setting to automatically serve the homepage at the root url of the domain from an `index.html` file.

It adds the `SFP_HANDLE_HOMEPAGE` thats defaults to `False` to not interfere with the current behavior.

### CODE REVIEW

**Comment by bradmontgomery** [comment]
Hi @synw, thank you for the work you've done here. I appreciate it, and I'm sorry to take so very long in giving you feedback.  

I really don't want to change the name of the package for this project. Additionally, even tho there have been not commits in a while, this project is far from dead. It's in use in many places, and still works well.

I'm happy to pull your edits to allow serving `index.html` files, but I'll do so without changing the project name.

**Comment by synw** [comment]
Hi. I changed the name after some time because of the lack of response, so I decided to maintain my own fork that's why. I can pr with just the index modification if you want. If this module is maintained I don't need a fork.
I also made the doc a little more simple. Would you be interested by this?

**Comment by bradmontgomery** [comment]
Sure, I'd also consider any changes to the docs, as well.

**Comment by bradmontgomery** [comment]
I'm closing this as the requested feature (ability to use an `index.html` template) has been added in #8.

**Pull request closed without merging**
